language: ruby
rvm:
- 2.6.3
- 2.5.5
- 2.4.6
before_script:
- gem install bundler
- cd pi_customizer/ && bundle install && cd ..
- cd pi_build_modifier/ && bundle install && cd ..
script:
- rake spec
deploy:
- provider: rubygems
  gem: pi_customizer
  gemspec: pi_customizer/pi_customizer.gemspec
  on:
    ruby: 2.6.3
  api_key:
    secure: "$TEST"
- provider: rubygems
  gem: pi_build_modifier
  gemspec: pi_build_modifier/pi_build_modifier.gemspec
  on:
    ruby: 2.6.3
  api_key:
    secure: "$TEST"

