# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'fileutils'

$dependencies = <<SCRIPT
sudo apt update
sudo apt -y upgrade
sudo apt -y install git curl quilt parted qemu-user-static debootstrap zerofree pxz zip dosfstools libcap2-bin bsdtar
SCRIPT

$modify = <<SCRIPT
# install gem
# execute gem with parameters
SCRIPT

Vagrant.configure('2') do |config|

  ROOT = 'envs/vagrant/'

  config.vm.box = 'debian/stretch64'
  config.disksize.size = '20GB'

  # Prepare environment by updating the dependencies
  config.vm.provision 'shell', inline: $dependencies

  # Copy config file
  #config.vm.provision 'file' --- config file

  # Actually modify and build
  config.vm.provision 'shell', inline: $modify

end
