# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'fileutils'

$dependencies = <<SCRIPT
sudo apt update
sudo apt -y upgrade
sudo apt -y install quilt parted qemu-user-static debootstrap zerofree pxz zip dosfstools libcap2-bin bsdtar
sudo apt -y install git curl ruby-full
SCRIPT

$prepare = <<SCRIPT
# install gem
if [ -f "pi_build_modifier.gem" ]; then
  echo "Gem exists"
else
  gem install --local pi_build_modifier.gem
end
mkdir /build/pi-gen
if [ -f "/build/pi-gen" ]; then
  git clone https://github.com/ottenwbe/pi-gen.git /build/pi-gen
else
  git pull https://github.com/ottenwbe/pi-gen.git -r
end
SCRIPT

$modify = <<SCRIPT
# Execute gem with parameters
pi_build_modifier ~/conf.json
SCRIPT

Vagrant.configure('2') do |config|

  config.vm.box = 'debian/stretch64'
  config.disksize.size = '20GB'

  # Prepare environment by updating the dependencies
  config.vm.provision 'shell', inline: $dependencies

  # Copy config file
  config.vm.provision "file", source: "conf.json", destination: "~/conf.json"

  if File.exists? pi_build_modifier.gem
    config.vm.provision "file", source: "pi_build_modifier.gem", destination: "~/pi_build_modifier.gem"
  else
    raise 'Config file cannot be found!'
  end

  # Actually modify and build
  config.vm.provision 'shell', inline: $prepare

  # Actually modify the build sources and build the environment
  config.vm.provision 'shell', inline: $modify

end
