# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'fileutils'

Vagrant.configure("2") do |config|

  config.vm.box = "debian/stretch64"

  config.vm.provision 'file', source: "../sh/build-pi-img.sh", destination: 'build-pi-img.sh'
  config.vm.provision 'file', source: "../../conf", destination: 'conf'

  if File.directory?('../../../pi-gen') then
    config.vm.provision 'file', source: "../../../pi-gen", destination: 'pi-gen'
  elsif File.file?('../../gitpath')
    config.vm.provision 'file', source: "../../gitpath", destination: 'pi-gen'
  end

  config.vm.provision 'shell', inline: <<-SHELL
    source build-pi-img.sh
  SHELL

end
