# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'fileutils'

Vagrant.configure('2') do |config|

  ROOT = '../../'

  config.vm.box = 'debian/stretch64'

  config.vm.provision 'file', source: ROOT+'envs/sh/build-pi-img.sh', destination: 'build-pi-img.sh'
  config.vm.provision 'file', source: ROOT+'conf', destination: 'conf'

  if File.directory?(ROOT+'../pi-gen')
    config.vm.provision 'file', source: ROOT+'../pi-gen', destination: 'pi-gen'
  end

  config.vm.provision 'shell', inline: <<-SHELL
    source build-pi-img.sh
  SHELL

end
